import { get } from "http";
import Head from "next/head";
import { useForm, Controller } from "react-hook-form";
import { onBoardingSchema } from "~/utils/validator/userInput";
import { zodResolver } from "@hookform/resolvers/zod";
import { useSession, signOut } from "next-auth/react";
export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data: sessionData, status } = useSession();
  const {
    register,
    handleSubmit,
    control,
    formState: { errors, isValid, isSubmitting },
  } = useForm({
    resolver: zodResolver(onBoardingSchema),
    mode: "onBlur",
  });
  return (
    <>
      <Head>
        <title>soad mai?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div
          className="btn absolute right-5 top-5"
          onClick={() => {
            void signOut({ callbackUrl: "/" });
          }}
        >
          logout
        </div>
        <div className="container flex flex-col items-center justify-center gap-6 px-4 py-16 sm:gap-12 ">
          <div className="avatar">
            <div className="w-28 rounded-full">
              <img src="https://i.pravatar.cc/" />
            </div>
          </div>
          <h6 className="text-3xl font-extrabold tracking-tight text-secondary-content sm:text-[4rem]">
            <span className="text-[#8e0e19] delay-75 duration-300 ease-in-out">
              {`@${sessionData?.user?.name} `}
            </span>
            <span className="delay-75 duration-300 ease-in-out hover:text-[#8e0e19]">
              {"soad "}
            </span>
            <span className="delay-75 duration-300 ease-in-out hover:text-[#8e0e19]">
              mai?
            </span>
          </h6>
          <div className="grid w-full grid-rows-1 items-center gap-5 font-bold sm:justify-center">
            <div className="form-control ">
              <label className="label text-lg">
                <span className="label-text text-base">
                  Tell something about yourself
                </span>
              </label>
              <textarea
                className="textarea textarea-bordered h-24 w-full sm:w-96"
                placeholder="Bio"
                {...register("bio")}
              ></textarea>
            </div>
            <div className="flex w-full flex-row justify-between">
              <label className="label text-lg"> soad mai?</label>
              <Controller
                control={control}
                name={"soad"}
                render={({ field: { onChange, onBlur, value, ref } }) => (
                  <div className="join">
                    <input
                      className="btn join-item"
                      type="radio"
                      aria-label="soad"
                      onBlur={onBlur} // notify when input is touched
                      onChange={() => onChange(true)} // send value to hook form
                      checked={value === true}
                      ref={ref}
                    />
                    <input
                      className="btn join-item"
                      type="radio"
                      aria-label="mai soad"
                      onChange={() => onChange(false)} // send value to hook form
                      checked={value === false}
                      ref={ref}
                    />
                  </div>
                )}
              />
            </div>
            <div
              className={`btn w-full ${
                isValid ? "btn-secondary" : "btn-disabled"
              }`}
              // onClick={handleSubmit((data) => {

              // })}
            >
              Submit
            </div>
          </div>
          <div className="flex flex-col items-center gap-2"></div>
        </div>
      </main>
    </>
  );
}
