import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
// import Link from "next/link";
import { api } from "~/utils/api";
import Image from "next/image";
// import { getServerSession } from "next-auth/next"
// import { authOptions } from "./api/auth/[...nextauth]"

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });
  const { data: sessionData, status } = useSession();
  const { data: user } = api.onBoarding.checkOnboarded.useQuery({});
  return (
    <>
      <Head>
        <title>Intania SOAD MAI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}


