export const options = [
  { value: "video_games", label: "🎮 Video Games" },
  { value: "reading", label: "📚 Reading" },
  { value: "cooking", label: "🍳 Cooking" },
  { value: "traveling", label: "✈️ Traveling" },
  { value: "music", label: "🎵 Music" },
  { value: "painting", label: "🎨 Painting" },
  { value: "basketball", label: "🏀 Basketball" },
  { value: "soccer", label: "⚽ Soccer" },
  { value: "swimming", label: "🏊 Swimming" },
  { value: "yoga", label: "🧘 Yoga" },
  { value: "chess", label: "♟️ Chess" },
  { value: "hiking", label: "🥾 Hiking" },
  { value: "dancing", label: "💃 Dancing" },
  { value: "coding", label: "💻 Coding" },
  { value: "gardening", label: "🌱 Gardening" },
  { value: "fashion", label: "👗 Fashion" },
  { value: "anime", label: "Anime" },
  { value: "fitness", label: "💪 Fitness" },
  { value: "writing", label: "📝 Writing" },
  { value: "baking", label: "🍰 Baking" },
  { value: "volleyball", label: "🏐 Volleyball" },
  { value: "puzzles", label: "🧩 Puzzles" },
  { value: "meditation", label: "🧘 Meditation" },
  { value: "cinema", label: "🎥 Cinema" },
  { value: "karaoke", label: "🎤 Karaoke" },
  { value: "cycling", label: "🚴 Cycling" },
  { value: "sketching", label: "🎨 Sketching" },
  { value: "running", label: "🏃 Running" },
  { value: "fishing", label: "🎣 Fishing" },
  { value: "cars", label: "🚗 Cars" },
  { value: "technology", label: "📱 Technology" },
  { value: "pets", label: "🐾 Pets" },
  { value: "beauty", label: "💅 Beauty" },
  { value: "shopping", label: "🛍️ Shopping" },
  { value: "comedy", label: "😄 Comedy" },
  { value: "history", label: "📜 History" },
  { value: "astronomy", label: "🔭 Astronomy" },
  { value: "football", label: "⚽ Football" },
  { value: "board_games", label: "🎲 Board Games" },
  { value: "call_of_duty", label: "🎮 Call of Duty" },
  { value: "fortnite", label: "🎮 Fortnite" },
  { value: "minecraft", label: "🎮 Minecraft" },
  { value: "apex_legends", label: "🎮 Apex Legends" },
  { value: "overwatch", label: "🎮 Overwatch" },
  { value: "counter_strike", label: "🎮 Counter-Strike" },
  { value: "valorant", label: "🎮 Valorant" },
  { value: "dota_2", label: "🎮 Dota 2" },
  { value: "hearthstone", label: "🎮 Hearthstone" },
  { value: "world_of_warcraft", label: "🎮 World of Warcraft" },
  { value: "grand_theft_auto", label: "🎮 Grand Theft Auto" },
  { value: "red_dead_redemption", label: "🎮 Red Dead Redemption" },
  { value: "among_us", label: "🎮 Among Us" },
  { value: "rocket_league", label: "🎮 Rocket League" },
  { value: "pubg", label: "🎮 PlayerUnknown's Battlegrounds" },
  { value: "fifa", label: "⚽ FIFA" },
  { value: "nba_2k", label: "🏀 NBA 2K" },
  { value: "warframe", label: "🎮 Warframe" },
  { value: "rainbow_six_siege", label: "🎮 Rainbow Six Siege" },
  { value: "league_of_legends", label: "🎮 League of Legends" },
  { value: "madden", label: "🏈 Madden NFL" },
  { value: "animal_crossing", label: "🏝️ Animal Crossing" },
  { value: "the_witcher", label: "🧙 The Witcher" },
  { value: "destiny", label: "🔮 Destiny" },
  { value: "god_of_war", label: "🎮 God of War" },
  { value: "super_smash_bros", label: "🎮 Super Smash Bros" },
];